const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.join(__dirname,'..');
const results=[];function test(name,fn){fn();results.push(name);console.log('PASS '+name);}
class Element{
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.attrs={};this.listeners={};this.hidden=false;this.disabled=false;this.value='';this.className='';this.textContent='';this.open=false;this.inert=false;this.classList={toggle:(c,on)=>{const a=new Set(this.className.split(' ').filter(Boolean));if(on===undefined)on=!a.has(c);on?a.add(c):a.delete(c);this.className=[...a].join(' ');},remove:c=>this.classList.toggle(c,false),contains:c=>this.className.split(' ').includes(c)};}
 append(...items){this.children.push(...items);items.forEach(i=>i.parent=this);}replaceChildren(...items){this.children=[];this.append(...items);}setAttribute(k,v){this.attrs[k]=String(v);}get firstElementChild(){return this.children[0];}addEventListener(k,f){(this.listeners[k]??=[]).push(f);}focus(){}showModal(){this.open=true;}close(){this.open=false;}closest(sel){if(sel==='[data-players]')return this.dataset.players?this:null;if(sel.includes('input'))return this.tagName==='INPUT'?this:null;return null;}fire(k,e={}){if(k==='click'&&this.disabled)return;for(const f of this.listeners[k]||[])f({target:this,preventDefault(){},...e});}click(){this.fire('click');}
}
function setup({denyStorage=false,random}={}){
 const els={},html=fs.readFileSync(root+'/index.html','utf8');for(const match of html.matchAll(/<(\w+)[^>]*\bid="([^"]+)"[^>]*>/g)){const e=new Element(match[1]);e.hidden=/\bhidden\b/.test(match[0]);els[match[2]]=e;}
 const playerEls=Array.from({length:6},(_,i)=>{const b=new Element('button');b.dataset.players=i+1;return b;});
 const hostEls=['next','skip','answer','reset'].map(a=>{const b=new Element('button');b.dataset.host=a;return b;});
 const doc=new Element('document');doc.getElementById=id=>{assert(els[id],id);return els[id];};doc.createElement=tag=>new Element(tag);doc.querySelectorAll=s=>s==='[data-players]'?playerEls:s==='[data-host]'?hostEls:[];const extra={};doc.querySelector=s=>extra[s]??=new Element();
 let now=new Date('2026-09-06T10:00:00Z').getTime(),nextID=0;const scheduled=new Map(),storage=new Map();
 class Clock extends Date{constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}}
 const context={console,document:doc,window:{scrollTo(){},addEventListener(){}},localStorage:{getItem(k){if(denyStorage)throw Error();return storage.get(k)||null;},setItem(k,v){if(denyStorage)throw Error();storage.set(k,v);}},navigator:{},location:{protocol:'http:'},confirm:()=>true,Date:Clock,setInterval:(f,d)=>{scheduled.set(++nextID,{f,d,interval:true});return nextID;},clearInterval:id=>scheduled.delete(id),setTimeout:(f,d)=>{scheduled.set(++nextID,{f,d});return nextID;},clearTimeout:id=>scheduled.delete(id),Math:random?Object.assign(Object.create(Math),{random}):Math};
 vm.createContext(context);vm.runInContext(fs.readFileSync(root+'/questions.js','utf8'),context);let code=fs.readFileSync(root+'/app.js','utf8');code=code.replace(/\}\)\(\);\s*$/,`window.TEST={selectQuestions,start,next,answer,reset,tick,finish,dayKey,leaders,renderLeaders,attract,getSession:()=>session,getView:()=>view};})();`);vm.runInContext(code,context);
 return {ui:els,api:context.window.TEST,context,doc,playerEls,hostEls,storage,scheduled,advance:ms=>now+=ms,runInterval:d=>[...scheduled.values()].filter(e=>e.interval&&e.d===d).forEach(e=>e.f())};
}
const h=setup(),{api,ui}=h;
function clickAnswer(h,q,correct=true){if(q.type==='timeline'){const arr=correct?q.correctAnswer:[...q.correctAnswer].reverse();for(const v of arr)h.ui.answers.children.find(b=>b.dataset.value===v).click();h.ui['submit-order'].click();}else h.ui.answers.children.find(b=>correct?b.dataset.value===q.correctAnswer:b.dataset.value!==q.correctAnswer).click();}
test('52 records, category minimums, unique IDs and valid answer schema',()=>{const q=h.context.window.SIRAH_QUESTIONS;assert.equal(q.length,52);assert.equal(new Set(q.map(x=>x.id)).size,52);for(const [cat,n] of Object.entries({Peristiwa:12,Tokoh:10,Tempat:8,'Susun Peristiwa':8,'Nilai & Ibrah':8,Mystery:6}))assert(q.filter(x=>x.category===cat).length>=n);q.forEach(q=>{assert.equal(new Set(q.options).size,q.options.length);if(q.type==='timeline'){assert.equal(q.options.length,3);assert.deepEqual([...q.options].sort(),[...q.correctAnswer].sort());assert.equal(q.points,120);}else{assert.equal(q.options.length,4);assert(q.options.includes(q.correctAnswer));assert.equal(q.points,q.category==='Mystery'?150:100);}});});
test('1,000 randomized sessions: 10 unique IDs/topics, two timeline + two ibrah, occasional Mystery',()=>{let mystery=0;const sets=new Set();for(let i=0;i<1000;i++){const q=api.selectQuestions();assert.equal(q.length,10);assert.equal(new Set(q.map(x=>x.id)).size,10);assert.equal(new Set(q.map(x=>x.topic)).size,10);assert.equal(q.filter(x=>x.type==='timeline').length,2);assert.equal(q.filter(x=>x.category==='Nilai & Ibrah').length,2);mystery+=q.some(x=>x.category==='Mystery');sets.add(q.map(x=>x.id).join(','));}assert(mystery>400&&mystery<720);assert(sets.size>990);});
test('Team input, all 1–6 participant choices and 4:00 start',()=>{for(let n=1;n<=6;n++){ui.players.fire('click',{target:h.playerEls[n-1]});ui['team-name'].value='Pasukan Umi';ui['start-form'].fire('submit');assert.equal(api.getSession().players,n);assert.equal(api.getSession().team,'Pasukan Umi');assert.equal(ui.timer.textContent,'4:00');assert.equal(ui.journey.children.length,10);}});
test('Host Next cannot bypass unanswered checkpoint; keyboard gated when host closed',()=>{h.doc.fire('keydown',{key:'n'});assert.equal(api.getSession().index,0);api.next();assert.equal(api.getSession().index,0);});
test('MCQ scoring and fast bonus; repeated tap cannot award twice',()=>{const q=api.getSession().questions[0];h.advance(9000);clickAnswer(h,q);assert.equal(api.getSession().score,q.points+25);clickAnswer(h,q);assert.equal(api.getSession().score,q.points+25);assert(!ui.feedback.hidden);});
test('Correct answer after 10 seconds receives base points only',()=>{api.next();const q=api.getSession().questions[1],before=api.getSession().score;h.advance(10001);clickAnswer(h,q);assert.equal(api.getSession().score-before,q.points);});
test('Wrong answer scores zero and exposes correct answer + explanation',()=>{api.next();const s=api.getSession(),q=s.questions[s.index],before=s.score;clickAnswer(h,q,false);assert.equal(s.score,before);assert(ui.feedback.children.some(x=>String(x.textContent).includes(q.correctAnswer)));});
test('Timeline tap ordering, undo, deselect, submit locking and 120+25 scoring',()=>{api.next();const s=api.getSession(),q=s.questions[s.index];assert.equal(q.type,'timeline');assert(ui['submit-order'].disabled);ui.answers.children[0].click();assert.equal(ui.answers.children[0].firstElementChild.textContent,1);ui.answers.children[0].click();assert.equal(ui.answers.children[0].firstElementChild.textContent,'–');ui.answers.children[0].click();ui['undo-order'].click();assert(ui['submit-order'].disabled);const before=s.score;clickAnswer(h,q);assert.equal(s.score-before,145);assert(ui['undo-order'].disabled);});
test('Ten checkpoints end in results; correct, accuracy, time, score and leaderboard',()=>{api.next();for(let i=4;i<9;i++){const s=api.getSession();clickAnswer(h,s.questions[s.index]);api.next();}const s=api.getSession();clickAnswer(h,s.questions[s.index]);api.next();assert.equal(api.getView(),'result');assert.equal(ui['result-correct'].textContent,'9 / 10');assert.equal(ui['result-accuracy'].textContent,'90%');assert.equal(ui['performance'].textContent,'Excellent');assert.equal(api.leaders().length,1);assert.equal(Number(ui['result-score'].textContent),s.score);});
test('Replay preserves team + participants; new team resets in one action',()=>{ui.replay.click();assert.equal(api.getSession().team,'Pasukan Umi');assert.equal(api.getSession().players,6);assert.equal(api.getSession().score,0);assert.equal(ui['undo-order'].disabled,false);api.finish('timeout');ui['new-team'].click();assert.equal(api.getView(),'start');assert.equal(ui['team-name'].value,'');assert.equal(h.playerEls[0].attrs['aria-pressed'],'true');});
test('Timer amber at 1:00, red at 0:20, timeout at 0 including background elapsed time',()=>{api.start();h.advance(180000);api.tick();assert(ui['timer-box'].classList.contains('amber'));assert.equal(ui.timer.textContent,'1:00');h.advance(40000);api.tick();assert(ui['timer-box'].classList.contains('red'));h.advance(20000);h.doc.fire('visibilitychange');assert.equal(api.getView(),'result');assert.equal(ui['result-time'].textContent,'4:00');assert.equal(ui['result-heading'].textContent,'MASA TAMAT!');assert.equal(ui['result-accuracy'].textContent,'0%');});
test('Answer at/after deadline is rejected without awarding points',()=>{api.start();h.advance(240001);clickAnswer(h,api.getSession().questions[0]);assert.equal(api.getSession().score,0);assert.equal(api.getView(),'result');});
test('Host shortcuts A/N/S/R, no scoring on reveal/skip, input typing safe',()=>{ui['host-toggle'].click();api.start();h.doc.fire('keydown',{key:'a',target:new Element('input')});assert.equal(api.getSession().records.length,0);h.doc.fire('keydown',{key:'a'});assert.equal(api.getSession().records[0].reason,'reveal');assert.equal(api.getSession().score,0);h.doc.fire('keydown',{key:'n'});assert.equal(api.getSession().index,1);h.doc.fire('keydown',{key:'s'});assert.equal(api.getSession().records[1].reason,'skip');h.doc.fire('keydown',{key:'r'});assert.equal(api.getView(),'start');});
test('Attract after 30 seconds, touch return, inert background; never interrupts game',()=>{h.advance(30001);h.runInterval(1000);assert(!ui.attract.hidden);assert(ui.main.inert);ui.attract.fire('pointerdown');assert(ui.attract.hidden);assert(!ui.main.inert);assert.equal(api.getView(),'start');api.start();h.advance(31000);h.runInterval(1000);assert(ui.attract.hidden);});
test('Perfect sessions produce Champion and exact set maximum (1290, 1340 or 1390)',()=>{for(let n=0;n<30;n++){api.start();for(let i=0;i<10;i++){const s=api.getSession();clickAnswer(h,s.questions[i]);api.next();}assert.equal(api.getSession().score,api.getSession().maxScore);assert([1290,1340,1390].includes(api.getSession().score));assert.equal(ui['performance'].textContent,'SIRAH CHAMPION');}});
test('Leaderboard top 5 sorted by score and time; date rollover and reset',()=>{let rows=api.leaders();assert.equal(rows.length,5);assert(rows.every((r,i)=>!i||rows[i-1].score>=r.score));h.advance(86400000);assert.equal(api.leaders().length,0);api.start();api.finish('timeout');assert.equal(api.leaders().length,1);ui['clear-leaders'].click();assert.equal(api.leaders().length,0);});
test('Sound settings and last team score persist through localStorage API',()=>{ui.sound.click();assert(JSON.parse(h.storage.get('sirah-journey-v1:settings')).sound);assert(JSON.parse(h.storage.get('sirah-journey-v1:score')).complete);});
test('Storage blocked or corrupt does not prevent game play',()=>{const d=setup({denyStorage:true});d.api.start();for(let i=0;i<10;i++){clickAnswer(d,d.api.getSession().questions[i]);d.api.next();}assert.equal(d.api.getView(),'result');assert.equal(d.api.leaders().length,1);h.storage.set('sirah-journey-v1:leaders','{corrupt');assert.doesNotThrow(()=>api.renderLeaders());});
test('User-supplied name rendered as text, not interpreted markup',()=>{ui['team-name'].value='<img src=x onerror=alert(1)>';api.start();api.finish('timeout');assert.equal(ui['result-team'].textContent,'<img src=x onerror=alert(1)>');assert.equal(ui['result-team'].children.length,0);});
test('Install fallback dialog opens and closes',()=>{ui.install.click();assert(ui['install-info'].open);ui['close-install'].click();assert(!ui['install-info'].open);});
test('HTML references exist; manifest scopes relative; icons dimensions; RTL and responsive CSS declared',()=>{const html=fs.readFileSync(root+'/index.html','utf8');for(const m of html.matchAll(/(?:src|href)="\.\/([^"]*)"/g))assert(fs.existsSync(path.join(root,m[1])));const manifest=JSON.parse(fs.readFileSync(root+'/manifest.webmanifest'));assert.equal(manifest.start_url,'./');assert.equal(manifest.scope,'./');for(const icon of manifest.icons){const b=fs.readFileSync(path.join(root,icon.src));assert.equal(`${b.readUInt32BE(16)}x${b.readUInt32BE(20)}`,icon.sizes);}assert(html.includes('lang="ar" dir="rtl"'));const css=fs.readFileSync(root+'/styles.css','utf8');assert(css.includes('@media(max-width:720px)'));assert(css.includes('min-height:76px'));assert(css.includes('prefers-reduced-motion'));assert(css.includes('Baloo2-Variable.woff2'));assert(fs.existsSync(path.join(root,'fonts/Baloo2-Variable.woff2')));assert(css.includes('NotoNaskhArabic-Variable.woff2'));assert(fs.existsSync(path.join(root,'fonts/NotoNaskhArabic-Variable.woff2')));});
(async()=>{
 const events={},cacheStore=new Map(),scope='http://localhost:8080/';let claimed=false,networkOffline=false;
 const cache={addAll:async assets=>{for(const item of assets){const file=item==='./'?'index.html':item.slice(2);assert(fs.existsSync(path.join(root,file)));cacheStore.set(new URL(item,scope).href,fs.readFileSync(path.join(root,file),'utf8'));}},match:async(req)=>cacheStore.get(new URL(typeof req==='string'?req:req.url,scope).href.split('?')[0])};
 const caches={open:async()=>cache,keys:async()=>['sirah-journey-old','unrelated-app'],delete:async key=>{assert.equal(key,'sirah-journey-old');return true;}};
 let skippedWaiting=false;
 const sw={self:{location:{origin:'http://localhost:8080'},clients:{claim:async()=>{claimed=true;}},skipWaiting:async()=>{skippedWaiting=true;},addEventListener:(n,f)=>events[n]=f},caches,URL,fetch:async()=>{if(networkOffline)throw Error('offline');return 'network';}};
 vm.runInNewContext(fs.readFileSync(root+'/sw.js','utf8'),sw);let wait;events.install({waitUntil:p=>wait=p});await wait;assert.equal(cacheStore.size,11);assert(skippedWaiting);results.push('SW install: all 11 required assets precached, skipWaiting called so one reload adopts a new deploy');events.activate({waitUntil:p=>wait=p});await wait;assert(claimed);results.push('SW activation: prior app cache removed, unrelated cache retained, clients claimed');networkOffline=true;for(const route of ['index.html','app.js','styles.css','questions.js','manifest.webmanifest','fonts/Baloo2-Variable.woff2','fonts/NotoNaskhArabic-Variable.woff2','icons/icon-192.png','icons/icon-512.png','icons/icon-maskable-512.png','']){let response;events.fetch({request:{method:'GET',url:scope+route,mode:route===''?'navigate':'cors'},respondWith:p=>response=p});assert(await response);}results.push('SW fetch: cached app, question data, styles, manifest, fonts and icons served with network unavailable');let response;events.fetch({request:{method:'GET',url:scope+'fallback',mode:'navigate'},respondWith:p=>response=p});assert((await response).startsWith('<!doctype html>'));results.push('SW offline navigation fallback serves index');
 const report=`SIRAH JOURNEY — QA REPORT\nDate: 2026-09-10\n\nPASS (${results.length} groups)\n${results.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\nMETHOD AND LIMITATIONS\nFunctional checks run against app.js in Node VM with a simulated DOM, clock,\nlocalStorage and service worker/cache environment. Shipping source is unchanged\nby test instrumentation. Static checks cover references, PNG dimensions,\nmanifest, RTL attributes and CSS breakpoints. JavaScript syntax checked with Node.\n\nThese are NOT real-browser/end-to-end tests. Actual Chrome/Edge installation,\nmobile visual rendering, Arabic font appearance, physical touchscreen, browser\ncache eviction and OS double-click launch were not exercised in this environment.\nThe available Sites preview does not support this plain static project.\nWindows/Mac launch scripts were inspected; Python server syntax checked.\nBefore booth use, open the ZIP on the actual device, complete one game, wait for\nSedia offline, install if offered, and verify launch once with internet off.\n`;
 fs.writeFileSync(root+'/QA_REPORT.txt',report);console.log(`PASS ${results.length} groups total`);
})().catch(e=>{console.error(e);process.exitCode=1;});
